### ISSUE TITLE
FEATURE REQUEST: Mechanism to label canisters that are listed in the "Canisters" tab

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/nns-dapp#1006]
Since a lot of individuals (myself included) use the NNS UI to manage cycle balances and topups for canisters, it quickly becomes unwieldy to try and identify which canister is for what project using just the canister principal IDs.
A mechanism to add some sort of identifying label to each canister listed in the canisters tab would help greatly in organizing canisters by what project they belong to.

**Comment by peterpeterparker** [comment]
We definitely want to support being able to set name for canisters in NNS-dapp in the future, agree with you. We already had some discussions about it but still have some UX questions to resolve before going further.

**Comment by saikatdas0790** [comment]
Hi @peterpeterparker 

Any movement on this? Apart from governance, the NNS dapp serves as a great dashboard to organize canisters that you control as a dapp developer

**Comment by peterpeterparker** [comment]
@saikatdas0790 not really. We discussed it again in the team and we are still super motivated to add such a feature but, on the other side, we do not think we should just implement the field in NNS-dapp only.

i.e. rather that a labelled field save within the NNS-dapp canister, it would be more handy to have a meta label information within the canister so that whereever you use canister, you can access the meta data.

However, there is currently no such meta data for canister in the IC specification.

Being said, I know there are some plan to bring some love to the canister screens at some point. I hope we can move this a bit forward at that time.

**Comment by peterpeterparker** [comment]
Ultimately [above idea](https://github.com/dfinity/nns-dapp/issues/1006#issuecomment-1347827449) was no followed and no metadata of the canister at the protocol level will be used. The team decided and implemented then sort of "name / label" information you mention within the dapp - i.e. the information will live within NNS dapp canister and will be available in NNS dapp UI. This was notably implemented in #2808 and will be proposed with next proposal. Therefore I mark this feature request as closed.
