### ISSUE TITLE
Do not save ic-delegation and ic-identity to local storage

### ISSUE THREAD

**Issue by cybrowl** [dfinity/nns-dapp#275]
The login flow should be similar to the identity app. It does not save those cookies. If a browser is compromised, the logging of those cookies would allow the attacker to take over.

**Comment by peterpeterparker** [comment]
Delegation and identity are saved in idb with a expiry time of 30 minutes. In addition, several CSP rules are applied to avoid attacker to compromise the data and a web worker cronjob signout automatically the user if the delegation experies. The login flow uses post message - i.e. there is not cookie with the communication with II. Therefore and since the security team also had no requirement to not use idb, I'll close this request as I am doing some cleanup and because it has been opened for a while. If you have good arguments and examples to reopen it, for sure ping me.
