### ISSUE TITLE
Please improve error messages

### ISSUE THREAD

**Issue by JensGroth** [dfinity/nns-dapp#684]
All error messages I've seen are laconic. E.g., I deliberately tried merging maturity in an erroneous way and got "No compatible device found".
May I suggest a review of all error messages with a view towards helping the user to resolve the issues they encounter when hitting an error. E.g., for the above error, perhaps it would be a link to relevant documentation or a list of compatible devices.

**Comment by lmuntanerDfinity** [comment]
Thanks for the feedback. Since we are rewriting the app in Svelte, we intend to make some quick UX improvements.

Better error management is one of them. Maybe not from the first version, but once we have the Svelte application, we will be faster improving UX and implementing feedback from the users.

As a start, we intend to hide or disable actions that we know beforehand are not allowed. Depending on the case, we might disable and show a tooltip or hide the button altogether if the user can't perform that action.

**Comment by peterpeterparker** [comment]
The dapp has changed a lot since this issue was raised, therefore I'll go on and close it. Don't hesitate to open particular issue if you notice one particular message that should be improved, that would help!
